[
    { "name": "Abyssinian", "weight_imperial": "7 - 10" },
    { "name": "Aegean", "weight_imperial": "7 - 10" },
    { "name": "American Bobtail", "weight_imperial": "7 - 16" },
    { "name": "American Curl", "weight_imperial": "5 - 10" },
    { "name": "American Shorthair", "weight_imperial": "8 - 15" },
    { "name": "American Wirehair", "weight_imperial": "8 - 15" },
    { "name": "Arabian Mau", "weight_imperial": "8 - 16" },
    { "name": "Australian Mist", "weight_imperial": "7 - 15" },
    { "name": "Balinese", "weight_imperial": "4 - 10" },
    { "name": "Bambino", "weight_imperial": "4 - 9" },
    { "name": "Bengal", "weight_imperial": "6 - 12" },
    { "name": "Birman", "weight_imperial": "6 - 15" },
    { "name": "Bombay", "weight_imperial": "6 - 11" },
    { "name": "British Longhair", "weight_imperial": "8 - 18" },
    { "name": "British Shorthair", "weight_imperial": "12 - 20" },
    { "name": "Burmese", "weight_imperial": "6 - 12" },
    { "name": "Burmilla", "weight_imperial": "6 - 13" },
    { "name": "California Spangled", "weight_imperial": "10 - 15" },
    { "name": "Chantilly-Tiffany", "weight_imperial": "7 - 12" },
    { "name": "Chartreux", "weight_imperial": "6 - 15" },
    { "name": "Chausie", "weight_imperial": "7 - 15" },
    { "name": "Cheetoh", "weight_imperial": "8 - 15" },
    { "name": "Colorpoint Shorthair", "weight_imperial": "4 - 10" },
    { "name": "Cornish Rex", "weight_imperial": "5 - 9" },
    { "name": "Cymric", "weight_imperial": "8 - 13" },
    { "name": "Cyprus", "weight_imperial": "8 - 16" },
    { "name": "Devon Rex", "weight_imperial": "5 - 10" },
    { "name": "Donskoy", "weight_imperial": "10 - 12" },
    { "name": "Dragon Li", "weight_imperial": "9 - 12" },
    { "name": "Egyptian Mau", "weight_imperial": "6 - 14" },
    { "name": "European Burmese", "weight_imperial": "7 - 14" },
    { "name": "Exotic Shorthair", "weight_imperial": "7 - 14" },
    { "name": "Havana Brown", "weight_imperial": "6 - 10" },
    { "name": "Himalayan", "weight_imperial": "7 - 14" },
    { "name": "Japanese Bobtail", "weight_imperial": "5 - 10" },
    { "name": "Javanese", "weight_imperial": "5 - 10" },
    { "name": "Khao Manee", "weight_imperial": "8 - 12" },
    { "name": "Korat", "weight_imperial": "7 - 11" },
    { "name": "Kurilian", "weight_imperial": "8 - 15" },
    { "name": "LaPerm", "weight_imperial": "6 - 10" },
    { "name": "Maine Coon", "weight_imperial": "12 - 18" },
    { "name": "Malayan", "weight_imperial": "6 - 13" },
    { "name": "Manx", "weight_imperial": "7 - 13" },
    { "name": "Munchkin", "weight_imperial": "5 - 9" },
    { "name": "Nebelung", "weight_imperial": "7 - 11" },
    { "name": "Norwegian Forest Cat", "weight_imperial": "8 - 16" },
    { "name": "Ocicat", "weight_imperial": "7 - 15" },
    { "name": "Oriental", "weight_imperial": "5 - 10" },
    { "name": "Persian", "weight_imperial": "9 - 14" },
    { "name": "Pixie-bob", "weight_imperial": "8 - 17" },
    { "name": "Ragamuffin", "weight_imperial": "8 - 20" },
    { "name": "Ragdoll", "weight_imperial": "12 - 20" },
    { "name": "Russian Blue", "weight_imperial": "5 - 11" },
    { "name": "Savannah", "weight_imperial": "8 - 25" },
    { "name": "Scottish Fold", "weight_imperial": "5 - 11" },
    { "name": "Selkirk Rex", "weight_imperial": "6 - 16" },
    { "name": "Siamese", "weight_imperial": "8 - 15" },
    { "name": "Siberian", "weight_imperial": "8 - 16" },
    { "name": "Singapura", "weight_imperial": "5 - 8" },
    { "name": "Snowshoe", "weight_imperial": "7 - 12" },
    { "name": "Somali", "weight_imperial": "6 - 12" },
    { "name": "Sphynx", "weight_imperial": "6 - 12" },
    { "name": "Tonkinese", "weight_imperial": "6 - 12" },
    { "name": "Toyger", "weight_imperial": "7 - 15" },
    { "name": "Turkish Angora", "weight_imperial": "5 - 10" },
    { "name": "Turkish Van", "weight_imperial": "7 - 20" },
    { "name": "York Chocolate", "weight_imperial": "12 - 18" }
]

